###########
# site.title, site.url, site.author.name

title:   'Yung-Hsing Wu'
author:
  name:  'Yung-Hsing Wu'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: 'https://johnlaudun.github.io/yhw.' 
url:  'https://yhwu.net'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

